EOD Change controlnumber in otherPhysicalFormat
libris/librisxl pull request #1175
Opened 2022-11-15 07:58 UTC by poacherone

Fix for faulty controlnumbers in otherPhysicalFormat for some EOD records.

2022-11-15 16:48 UTC, niklasl commented
If the controlnumbers are from real records, change the local (blank) `otherPhysicalFormat` to a link instead. (Or `reproductionOf` if that is the case here?)

2022-12-20 10:30 UTC, poacherone commented
Changed to adding reproductionOf. @niklasl

2022-12-20 16:49 UTC, niklasl requested changes
Some small fixes (and another test run, perhaps in STG) should be all to make this work!

2022-12-20 16:49 UTC, niklasl commented on whelktool/scripts/syslib/change-otherphysicalformat-controlnumber.groovy
> +    where = """id in
Needs to be local (to avoid being overwritten by another thread):
```suggestion
    def where = """id in
```

2022-12-20 16:49 UTC, niklasl commented on whelktool/scripts/syslib/change-otherphysicalformat-controlnumber.groovy
> +            bib.graph[1].remove('otherPhysicalFormat')
Might not be the case here, but in general, check if there is more than one item in `otherPhysicalFormat` before dropping (unless any others are to be discarded).

2022-12-20 16:49 UTC, niklasl commented on whelktool/scripts/syslib/change-otherphysicalformat-controlnumber.groovy
> +                    ["@id": "https://libris-qa.kb.se/$newCtrlnr#it"]
Tied to the QA environment, won't work in Prod. Use `findCanonicalId(newCtrlnr)` to get the main id from the record id.

2022-12-21 11:52 UTC, poacherone commented
Added new script to fix reproductionOf (on the correct records!).

2022-12-21 17:23 UTC, niklasl approved these changes
I believe my concerns have been addressed. (Alas, I don't have much time to verify, so do make another test run or ask for a second glance in case of doubt though.)

*NOTE* I do think making the checks before dropping `otherPhysicalFormat` are prudent (e.g. using `assert` which will fail if the assumptions don't hold).

(And once run in QA or STG, check that the links work and that, from these, the expected bib 773 MARC21 is present.)

2022-12-21 20:46 UTC, poacherone commented
I have made a test run on QA and will do another one on STG to make sure all the links work correct. 776 (as is the case here) is present in the conversion to MARC21.

2022-12-22 10:02 UTC, merged