Add more fine-grained merge rules for SAB classification
libris/librisxl pull request #1322
Opened 2023-11-06 15:05 UTC by kwahlin

Rules explained in https://jira.kb.se/browse/FMT-204

2023-11-07 14:37 UTC, andand79 approved these changes
Très bien!

2023-11-08 15:15 UTC, olovy requested changes
I think this needs some tests
Also: see comment about startsWithExceptions.

I don't suggest changing the implementation but the code is a bit hard to follow. It could be made clearer by for instance by making it more explicit what the sabPrecedenceRules data structure contains.

2023-11-08 15:15 UTC, olovy commented on librisworks/src/main/groovy/se/kb/libris/mergeworks/compare/Classification.groovy
> +        if (preferred && !(a =~ startsWithExceptions)) {
`startsWithExceptions` also apply to "equals?"
In that case the naming is a bit confusing.

2023-11-08 15:27 UTC, kwahlin commented
> I think this needs some tests
> 
> I don't suggest changing the implementation but the code is a bit hard to follow. It could be made clearer by for instance by making it more explicit what the sabPrecedenceRules data structure contains.

I agree. I was a bit eager to get this in quickly.

2023-11-08 15:30 UTC, olovy commented
> > I think this needs some tests
> > I don't suggest changing the implementation but the code is a bit hard to follow. It could be made clearer by for instance by making it more explicit what the sabPrecedenceRules data structure contains.
> 
> I agree. I was a bit eager to get this in quickly.

Just a couple of tests on `tryMergeSabCodes` or `merge` is fine

2023-11-09 10:36 UTC, olovy approved these changes
LGTM

See comment about `startsWithExceptions`

2023-11-09 14:01 UTC, merged