find API: add experimental spell checking
libris/librisxl pull request #1459
Opened 2024-08-01 10:24 UTC by andersju

A first stab at adding spell checking, to be used by Libris sök. Uses Elasticsearch's [phrase suggester](https://www.elastic.co/guide/en/elasticsearch/reference/8.13/search-suggesters.html#phrase-suggester) with two generators as described in the ES docs.

Uses `_sortKeyByLang.sv` as the field to get suggestions from, as it seems like a reasonable choice; with e.g.  `_all` we'd get lots of "bad" suggestions since it contains lots of oft-repeated vocab stuff. (sv vs en shouldn't matter for these purposes.)

Quick testing on the dev data is promising. We might want to tinker with both the suggester configuration/query and the field(s) to target. This is just somerthing to start with.

With `/find?q=foobar&_spell=true` the spell checking is done in _addition_ to the regular query and returned along with the usual results.

With `/find?q=foobar&_spell=only` _only_ the spell checking query is performed.

```
~ curl -s "http://localhost:8180/find?q=dynimical%20systems&_spell=true"|jq '._spell'
[
  {
    "text": "dynamical systems",
    "highlighted": "<em>dynamical</em> systems",
    "score": 0.005399387
  }
]
~ curl -s "http://localhost:8180/find?q=dynimical%20systemms&_spell=true"|jq '._spell'
[
  {
    "text": "dynamical systems",
    "highlighted": "<em>dynamical systems</em>",
    "score": 0.005399387
  }
]
```

curl directly against ES, local dev:
```
curl --request POST \
  --url https://localhost:9200/libris_local/_search \
  -k \
  -u elastic:elastic \
  --header 'Content-Type: application/json' \
  --data '{
  "suggest": {
    "text" : "dynimical system",
    "simple_phrase" : {
      "phrase" : {
        "field" : "_sortKeyByLang.sv.trigram",
        "size" : 1,
	"max_errors": 2,
        "direct_generator" : [
		{
			"field" : "_sortKeyByLang.sv.trigram",
			"suggest_mode" : "always"
        	},
		{
			"field" : "_sortKeyByLang.sv.reverse",
			"suggest_mode" : "always",
			"pre_filter" : "reverse",
			"post_filter" : "reverse"
      		}
	],
	"highlight": {
          "pre_tag": "<em>",
          "post_tag": "</em>"
        }
      }
    }
  }
}'
```

https://kbse.atlassian.net/browse/LWS-87

2024-08-01 19:40 UTC, olovy requested changes
Very nice!

* Agree that `_sortKeyByLang.sv` is a reasonable starting point
* Perhaps `_spell=true` should be the default. :thinking: Has performance implications though.
* `_spell=only` might be a good option for clients to do spell checking "on the side" with a separate request without slowing down the main search query.
* We probably want to promote `_spell` (or whatever we decide on) to an official vocab (non-underscore) term . Let's do this later.
* TODO: Add support in "new style" search API after https://github.com/libris/librisxl/pull/1455 is merged

Changes requested:
* I think we should provide a link to the corrected query in the alongside the suggestion. So that the client doesn't have to do any URL manipulation.
* I think we should remap the terms in the result to keep the API free from elasticsearch details. 

What about:
```
curl -s "http://localhost:8180/find?q=flyttning%20och%20peldning&%40type=Instance&_spell=true" | jq '._spell'
[
  {
    "label": "flyttning och <em>pendling</em>",
    "view": { "@id": "/find?q=flyttning%20och%20pendling&%40type=Instance&_spell=true" }
  }
]
```
?

(I don't think the score is useful?)

2024-08-02 09:53 UTC, andersju commented
@olovy Sounds good! See latest commit.

(Probably we wouldn't want to actually show suggestions unless there are no search hits (or perhaps very few hits?), otherwise there might often be annoying suggestions even if you spell correctly. Though this is something for the client to decide.)

2024-08-02 10:13 UTC, olovy commented on rest/src/main/groovy/whelk/rest/api/SearchUtils.groovy
> +                        'labelWithMarkup': suggestion['highlighted'],
```suggestion
                        'labelHTML': suggestion['highlighted'],
```

Found this usage of type coercion for description with type `rdf:HTML`.
We can stick to the same naming convention.

https://github.com/libris/definitions/blob/a320ff90c87a96e143826812a50afb0635c8cccd/source/app/help.jsonld#L12

2024-08-02 10:15 UTC, olovy approved these changes
LGTM!

See suggestion about using the same naming convention as `descriptionHTML`

2024-08-02 10:32 UTC, merged