boostedfields for query
libris/librisxl pull request #1510
Opened 2024-11-05 10:38 UTC by kaipoykio

Tentative attempt at boosting fields.

2024-11-12 15:11 UTC, kwahlin requested changes
Most of the stuff in [`BoostedFields`](https://github.com/libris/librisxl/blob/e11768dd0de7a574243df2ea8c805c8fe31936d7/whelk-core/src/main/groovy/whelk/search2/BoostedFields.groovy) is redundant, see [`EsMappings`](https://github.com/libris/librisxl/blob/e11768dd0de7a574243df2ea8c805c8fe31936d7/whelk-core/src/main/groovy/whelk/search2/EsMappings.java).

I suggest letting [`QueryParams`](https://github.com/libris/librisxl/blob/e11768dd0de7a574243df2ea8c805c8fe31936d7/whelk-core/src/main/groovy/whelk/search2/QueryParams.java) handle the parameters and move the boost computing stuff into [`QueryUtil`](https://github.com/libris/librisxl/blob/e11768dd0de7a574243df2ea8c805c8fe31936d7/whelk-core/src/main/groovy/whelk/search2/QueryUtil.java) (where all that is needed should be available).

2024-11-14 13:06 UTC, kaipoykio commented
new version...

2024-11-25 07:50 UTC, kwahlin reviewed
Nice! The entity type (determining which boosting mode to apply) needs to be fetched in a different way. See separate comment. 

Otherwise I think this should work...? Obviously needs some cleaning up too.

2024-11-26 07:09 UTC, kaipoykio commented on whelk-core/src/main/groovy/whelk/search2/QueryUtil.java
> +	String[] originalTypeParam = queryParameters.get("@type");
*thumbs up* ;)

2025-01-09 14:35 UTC, closed without merging

2025-01-09 14:35 UTC, olovy commented
Completed in https://github.com/libris/librisxl/pull/1531