Make multi-wildcard searches possible.
libris/librisxl pull request #794
Opened 2020-11-12 14:48 UTC by jannistsiroyannis

For example "*kol*" should match "skolor".
To do this, we're switching all instances of simple query strings, to
query strings (ES nomenclature).

Side-effects of this are:
1. Queries can now fail (must be handled)
2. Character escaping becomes necessary in implict filters.
3. Character escaping will also be necessary in the "search box" if such
   chars are ever used there.

2020-11-12 16:23 UTC, niklasl commented
As I recall, we switched *to* `simple_query_string` for good reasons, being simpler (thus exposing a simpler logic in the API, something which ES also recommends "for search boxes").

If there is no other way, I'd probably rather switch to full `query_string` *only* if the search matches something like `/\*\S+/` (or a more involved regex to control exactly what we expose), instead of attempting to escape, clean up and error handle the full query string DSL syntax (which is too much for our regular use cases).While non-obvious to the end-user, we might explain that we (experimentally) allow leading wildcard queries (unless they prove too expensive).

2020-11-12 16:49 UTC, olovy requested changes
LGTM except the escaping part.

It should be possible to use the operators described in [the search help](https://libris-stg.kb.se/katalogisering/help/search) when on e.g. prefLabel.
e.g. http://localhost:8080/katalogisering/search/libris?prefLabel=*kolor&%40type=Concept

We need to handle filtering on URIs as well so maybe something like
```
if (looksLikeUri(val))
    escape(val)
```
or
`ESreservedChars = "=><!{}[]^:/"` not enough?


I tried modifying `ESreservedChars` but this query still finds nothing when using `query_string` https://libris.kb.se/katalogisering/search/libris?prefLabel=%28tekniska%20%7C%20frist%C3%A5ende%29%20skolor&%40type=Concept
maybe we have to live with that.

2020-11-12 16:55 UTC, olovy commented
> LGTM except the escaping part.
> 
> It should be possible to use the operators described in [the search help](https://libris-stg.kb.se/katalogisering/help/search) when on e.g. prefLabel.
> e.g. http://localhost:8080/katalogisering/search/libris?prefLabel=*kolor&%40type=Concept
> 
> We need to handle filtering on URIs as well so maybe something like
> 
> ```
> if (looksLikeUri(val))
>     escape(val)
> ```
> 
> or
> `ESreservedChars = "=><!{}[]^:/"` not enough?
> 
> I tried modifying `ESreservedChars` but this query still finds nothing when using `query_string` https://libris.kb.se/katalogisering/search/libris?prefLabel=%28tekniska%20%7C%20frist%C3%A5ende%29%20skolor&%40type=Concept
> maybe we have to live with that.

This is of course obsoleted by the comment by Niklas

2020-11-16 11:59 UTC, olovy commented
I started doing something more fancy that could handle queries like `*foo | http://bar`, i.e. escaping characters in URIs when using `query_string` but I don't really see the need for it?

2020-11-16 13:33 UTC, jannistsiroyannis commented on whelk-core/src/main/groovy/whelk/search/ESQuery.groovy
> +        // The following chars are ES operators and need to be escaped to be used as literals: \+-=|&><!(){}[]^"~*?:/
Remove comment if no longer doing this?

2020-11-16 14:10 UTC, olovy commented on whelk-core/src/main/groovy/whelk/search/ESQuery.groovy
> +        // The following chars are ES operators and need to be escaped to be used as literals: \+-=|&><!(){}[]^"~*?:/
:+1:

2020-11-16 16:33 UTC, olovy approved these changes

2020-11-16 16:33 UTC, merged