Add script for jaktskildringar.
libris/librisxl pull request #909
Opened 2021-04-29 12:33 UTC by jannistsiroyannis

2021-04-29 13:57 UTC, olovy reviewed
LXL-3536 was a bit vague but as I understood it we also want to change subject: sao/Jaktskildringar to genreForm: saogf/Jaktskildringar?

gernreForm: sao/Jaktskildringar  are only 5 records [in PROD](https://libris.kb.se/katalogisering/search/libris?o=https%3A%2F%2Fid.kb.se%2Fterm%2Fsao%2FJaktskildringar) while  subject: sao/Jaktskildringar to genreForm are 79. 

ComplexSubject termComponent (45) I guess we can't do nothing about.

2021-04-30 07:21 UTC, jannistsiroyannis commented
:+1: I've checked with Viktoria and its _only_ subject we're supposed to change. I'll fix it.

2021-05-07 07:01 UTC, klngwll reviewed
I do agree the description of the issue is a bit vague. In general we don't have GenreForm terms in subjects so I would have guessed also the relation should have changed to genreForm.

2021-05-12 06:44 UTC, klngwll requested changes
So what I figured out is that the relationship for these should be changed from subject to genreForm as well.

2021-05-14 11:15 UTC, jannistsiroyannis commented
> So what I figured out is that the relationship for these should be changed from subject to genreForm as well.

Better now? :)

2021-05-14 13:02 UTC, olovy commented on whelktool/scripts/cleanups/2021/04/lxl-3536-jaktskildringar.groovy
> +        work.genreForm.add(["id" : newLinkTarget])
```suggestion
        work.genreForm.add(["@id" : newLinkTarget])
```

2021-05-14 13:02 UTC, olovy reviewed
Almost!

The rest LGTM

2021-05-14 13:29 UTC, klngwll approved these changes
LGTM

2021-05-17 07:25 UTC, jannistsiroyannis commented
> Almost!
> 
> The rest LGTM

Good catch! :)

2021-05-17 07:25 UTC, merged